# Generated by Django 3.2.8 on 2021-10-26 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify', models.BooleanField(default=False, verbose_name='Verify')),
                ('document_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_document_1', to='file.file', verbose_name='File 1')),
                ('document_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_document_2', to='file.file', verbose_name='File 2')),
                ('document_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_document_3', to='file.file', verbose_name='File 3')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
    ]
