# Generated by Django 3.2.8 on 2021-10-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='file.file', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='client',
            name='verify',
            field=models.BooleanField(default=None, null=True, verbose_name='Verify'),
        ),
    ]
