# Generated by Django 3.2.8 on 2021-10-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('client', '0003_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_document_1', to='file.file', verbose_name='File 1'),
        ),
    ]
