# Generated by Django 3.2.8 on 2021-10-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_document_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='verify',
        ),
    ]
