# Generated by Django 3.2.8 on 2021-10-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default='user', max_length=30, verbose_name='user type'),
        ),
    ]
