# Generated by Django 3.2.8 on 2021-10-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verify',
            field=models.BooleanField(default=None, null=True, verbose_name='Verify'),
        ),
    ]
