# Generated by Django 3.2.8 on 2021-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_customuser_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify',
            field=models.CharField(blank=True, default='no', max_length=15, null=True, verbose_name='Verify'),
        ),
    ]
