# Generated by Django 3.2.8 on 2021-10-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_customuser_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verify',
            new_name='verification',
        ),
    ]
