# Generated by Django 3.2.8 on 2021-10-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_customuser_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending'), ('expired', 'Expired')], max_length=15, null=True),
        ),
    ]
